services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev

  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"
